services:
    minecraft:
        hostname: minecraft
        env_file: minecraft.env
        ports:
            - 25565:25565
#            - 25575:25575
        container_name: minecraft
        volumes:
            - ./data:/data
        image: itzg/minecraft-server:latest
        restart: unless-stopped