#!/usr/bin/env bash
asciilogo=$(cat gsh/messages/ascii-art/ascii-logo.txt)
echo "Have you made any changes to the current files that you'd like saved or would you like to save this version for later? yes/no:"
read ans
ans=$(echo "$ans" | awk '{print toupper($0)}')
if [ "$ans" == "YES" ]
then
    if [ -f /usr/bin/sudo ]
    then
        if [ $EUID -eq 0 ]
        then
            echo "$asciilogo"
            echo "Backing up current version to preserve the local changes. All backed up files will be in the gshbak directory located at $PWD"
            mkdir -p ./gshbak
            cp -r /usr/gsh ./gshbak
            echo "Backup completed!"
            echo "Overwriting files now"
            cp -r ./gsh /usr
            if ! [ -d /usr/gsh/environment ]
            then
                mkdir -p /usr/gsh/environment
                cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
                cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
            fi
            if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
            then
                cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
            fi
            if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
            then
                cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
            fi
            if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
            then
                cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
            fi
            if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
            then
                cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
            fi
            echo "Update Completed! Thank You! :)"
        elif [ $EUID -ge 1000 ]
        then
            echo "$asciilogo"
            echo "Backing up current version to preserve the local changes. All backed up files will be in the gshbak directory located at $PWD"
            mkdir -p ./gshbak
            cp -r /usr/gsh ./gshbak
            echo "Backup completed!"
            echo "Overwriting files now"
            sudo cp -r ./gsh /usr
            if ! [ -d /usr/gsh/environment ]
            then
                sudo mkdir -p /usr/gsh/environment
                sudo cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
                sudo cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
            fi
            if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
            then
                sudo cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
            fi
            if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
            then
                sudo cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
            fi
            if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
            then
                sudo cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
            fi
            if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
            then
                sudo cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
            fi
            echo "Update Completed! Thank You! :)"
        fi
    elif ! [ -f /usr/bin/sudo ]
    then
        echo "$asciilogo"
        echo "Backing up current version to preserve the local changes. All backed up files will be in the gshbak directory located at $PWD"
        mkdir -p ./gshbak
        cp -r /usr/gsh ./gshbak
        echo "Backup completed!"
        echo "Overwriting files now"
        cp -r ./gsh /usr
        if ! [ -d /usr/gsh/environment ]
        then
            mkdir -p /usr/gsh/environment
            cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
            cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
        fi
        if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
        then
            cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
        fi
        if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
        then
            cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
        fi
        if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
        then
            cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
        fi
        if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
        then
            cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
        fi
        echo "Update Completed! Thank You! :)"
    fi
elif [ "$ans" == "NO" ]
then
    if [ -f /usr/bin/sudo ]
    then
        if [ $EUID -eq 0 ]
        then
            echo "$asciilogo"
            echo "Updating now!"
            cp -r ./gsh /usr
            if ! [ -d /usr/gsh/environment ]
            then
                mkdir -p /usr/gsh/environment
                cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
                cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
            fi
            if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
            then
                cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
            fi
            if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
            then
                cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
            fi
            if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
            then
                cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
            fi
            if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
            then
                cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
            fi
            echo "Update Completed! Thank You! :)"
        elif [ $EUID -ge 1000 ]
        then
            echo "$asciilogo"
            echo "Updating now!"
            sudo cp -r ./gsh /usr
            if ! [ -d /usr/gsh/environment ]
            then
                sudo mkdir -p /usr/gsh/environment
                sudo cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
                sudo cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
            fi
            if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
            then
                sudo cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
            fi
            if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
            then
                sudo cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
            fi
            if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
            then
                sudo cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
            fi
            if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
            then
                sudo cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
            fi
            echo "Update Completed! Thank You! :)"
        fi
    elif ! [ -f /usr/bin/sudo ]
    then
        echo "$asciilogo"
        echo "Updating now!"
        cp -r ./gsh /usr
        if ! [ -d /usr/gsh/environment ]
        then
            mkdir -p /usr/gsh/environment
            cp ./examples/donation-ctrl.env /usr/gsh/environment/donation-ctrl.env
            cp ./examples/donation-ticker.env /usr/gsh/environment/donation-ticker.env
        fi
        if ! [ -f /usr/gsh/docker/factorio/factorio.env ]
        then
            cp ./examples/factorio.env /usr/gsh/docker/factorio/factorio.env
        fi
        if ! [ -f /usr/gsh/docker/satisfactory/satisfactory.env ]
        then
            cp ./examples/satisfactory.env /usr/gsh/docker/satisfactory/satisfactory.env
        fi
        if ! [ -f /usr/gsh/docker/minecraft/minecraft.env ]
        then
            cp ./examples/minecraft.env /usr/gsh/docker/minecraft/minecraft.env
        fi
        if ! [ -f /usr/gsh/docker/veloren/veloren.env ]
        then
            cp ./examples/veloren.env /usr/gsh/docker/veloren/veloren.env
        fi
        echo "Update Completed! Thank You! :)"
    fi
fi
