services:
  factorio:
    container_name: factorio
    image: factoriotools/factorio:latest
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ./factorio:/factorio
    restart: unless-stopped
    environment:
     - UPDATE_MODS_ON_START=true