services:
  factorio:
    container_name: factorio
    image: factoriotools/factorio:latest
    env_file: factorio.env
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ./:/factorio
    restart: unless-stopped