services:
  satisfactory:
    container_name: 'satisfactory'
    hostname: 'satisfactory'
    env_file: satisfactory.env
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - './config:/config'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G