#!/usr/bin/env bash
if ! [ -d /tmp/gsh ]
then
  mkdir -p /tmp/gsh
fi
if ! [ -f /tmp/gsh/donation-ticker.env ]
then
  touch /tmp/gsh/donation-ticker.env
fi
if [ -f /usr/bin/sudo ]
then
  if [ "$1" == "factorio" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      if [ "$3" == "--now" ]
      then
        docker compose -f /usr/gsh/docker/factorio/docker-compose.yml down
      else
        x=$(($(cat /usr/gsh/docker/factorio/config/server-settings.json | jq .autosave_interval)*60))
        while [ $x -ge 0 ]
        do
          if [ $x -gt 0 ]
          then
            clear
            printf '%dh:%dm:%ds\n' $(($x/3600)) $(($x%3600/60)) $(($x%60))
            x=$((x-1))
            sleep 0.999999999999
          else
            docker compose -f /usr/gsh/docker/factorio/docker-compose.yml down
            break
          fi
        done
      fi
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/factorio-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/factorio-help.txt
      printf '\n'
    fi
  elif [ "$1" == "satisfactory" ]
  then
    fi="/usr/gsh/docker/satisfactory/docker-compose.yml"
    envfi="/usr/gsh/docker/satisfactory/satisfactory.env"
    if [ "$2" == "up" ]
    then
      docker compose -f $fi up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f $fi down
    elif [ "$2" == "logs" ]
    then
      docker compose -f $fi logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f $fi pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f $fi logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f $fi restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f $fi up -d --force-recreate
    elif [ "$2" == "update" ]
    then
      curvar=$(cat $envfi | grep "SKIPUPDATE")
      repvar="SKIPUPDATE=false"
      cat $envfi
      sudo sed -i "s.$curvar.$repvar.g" $envfi
      cat $envfi
      docker compose -f $fi down
      docker compose -f $fi pull
      docker compose -f $fi up -d
      c=0
      while [[ $c -ne 1 ]]
      do
        docker compose -f $fi logs > /tmp/container-logs.log
        conterm="LogServer: Display: Server API listening on '0.0.0.0:7777'"
        if grep -Fq "$conterm" /tmp/container-logs.log
        then
          c=1
        else
          c=0
        fi
        sleep 5
      done
      docker compose -f $fi down
      cat $envfi
      sudo sed -i "s.$repvar.$curvar.g" $envfi
      cat $envfi
      docker compose -f $fi up -d
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/satisfactory-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/satisfactory-help.txt
      printf '\n'
    fi
  elif [ "$1" == "veloren" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml down
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/veloren-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/veloren-help.txt
      printf '\n'
    fi
  elif [ "$1" == "minecraft" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml down
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/minecraft-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/minecraft-help.txt
      printf '\n'
    fi
  elif [ "$1" == "uninstall" ]
  then
    bash /usr/gsh/script-files/uninstall
  elif [ "$1" == "--help" ]
  then
    cat /usr/gsh/messages/help/help.txt
    printf '\n'
  elif [ "$1" == "" ]
  then
    cat /usr/gsh/messages/help/help.txt
    printf '\n'
  fi
  source /usr/gsh/environment/donation-ctrl.env
  if [ "$donationmessage" -eq 0 ]
  then
    source /usr/gsh/environment/donation-ticker.env
    if [ $dt -ne 0 ]
    then
      if (( dt % 3 == 0 && dt % 10 == 0 ))
      then
        echo "Thank you for using 'Game Server Helper'. If you have found it helpful and would like to support the project, and others, please head on over to my KoFi: 'https://ko-fi.com/lollypopstealer'. Any support you can show would be greatly appreciated. Thank you again for using 'Game Server Helper'."
      fi
    fi
    dt=$(( $dt + 1 ))
    echo "dt=$dt" > /tmp/gsh/donation-ticker.env
    cp /tmp/gsh/donation-ticker.env /usr/gsh/environment/donation-ticker.env
  fi
else
  if [ "$1" == "factorio" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      if [ "$3" == "--now" ]
      then
        docker compose -f /usr/gsh/docker/factorio/docker-compose.yml down
      else
        x=$(($(cat /usr/gsh/docker/factorio/config/server-settings.json | jq .autosave_interval)*60))
        while [ $x -ge 0 ]
        do
          if [ $x -gt 0 ]
          then
            clear
            printf '%dh:%dm:%ds\n' $(($x/3600)) $(($x%3600/60)) $(($x%60))
            x=$((x-1))
            sleep 0.999999999999
          else
            docker compose -f /usr/gsh/docker/factorio/docker-compose.yml down
            break
          fi
        done
      fi
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/factorio/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/factorio-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/factorio-help.txt
      printf '\n'
    fi
  elif [ "$1" == "satisfactory" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f $fi up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f $fi down
    elif [ "$2" == "logs" ]
    then
      docker compose -f $fi logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f $fi pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f $fi logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f $fi restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f $fi up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/satisfactory-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/satisfactory-help.txt
      printf '\n'
    fi
  elif [ "$1" == "veloren" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml down
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/veloren/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/veloren-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/veloren-help.txt
      printf '\n'
    fi
  elif [ "$1" == "minecraft" ]
  then
    if [ "$2" == "up" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml up -d
    elif [ "$2" == "down" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml down
    elif [ "$2" == "logs" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml logs
    elif [ "$2" == "pull" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml pull
    elif [ "$2" == "tail-logs" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml logs -f
    elif [ "$2" == "restart" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml restart
    elif [ "$2" == "recreate" ]
    then
      docker compose -f /usr/gsh/docker/minecraft/docker-compose.yml up -d --force-recreate
    elif [ "$2" == "--help" ]
    then
      cat /usr/gsh/messages/help/minecraft-help.txt
      printf '\n'
    elif [ "$2" == "" ]
    then
      cat /usr/gsh/messages/help/minecraft-help.txt
      printf '\n'
    fi
  elif [ "$1" == "uninstall" ]
  then
    bash /usr/gsh/script-files/uninstall
  elif [ "$1" == "--help" ]
  then
    cat /usr/gsh/messages/help/help.txt
    printf '\n'
  elif [ "$1" == "" ]
  then
    cat /usr/gsh/messages/help/help.txt
    printf '\n'
  fi
  source /usr/gsh/environment/donation-ctrl.env
  if [ "$donationmessage" -eq 0 ]
  then
    source /usr/gsh/environment/donation-ticker.env
    if [ $dt -ne 0 ]
    then
      if (( dt % 3 == 0 && dt % 10 == 0 ))
      then
        echo "Thank you for using 'Game Server Helper'. If you have found it helpful and would like to support the project, and others, please head on over to my KoFi: 'https://ko-fi.com/lollypopstealer'. Any support you can show would be greatly appreciated. Thank you again for using 'Game Server Helper'."
      fi
    fi
    dt=$(($dt+1))
    echo "dt=$dt" > /tmp/gsh/donation-ticker.env
    cp /tmp/gsh/donation-ticker.env /usr/gsh/environment/donation-ticker.env
  fi
fi