#!/usr/bin/env bash
echo "Do you want to save your game-saves/mods directories? yes/no"
read ans
ans=$(echo $ans | awk '{print tolower($0)}')
if [ "$ans" == "yes" ]
then
    echo "Do you plan on playing them without the use of 'Game Server Helper' or should they be archived for safe keeping?"
    echo "Options: 1.Still Playing 2.Archive 3.Archive only"
    read num
    if [ $num -eq 1 ]
    then
        x=300
        stime=$x
        echo "Understood. Moving docker folder to $HOME and deleting /usr/gsh . Please ensure you have a backup of any custom files prior to running this script. If you do NOT have a backup of your custom files please press CTRL+C within the next $((x/60)) minutes otherwise your custom files, not including docker folder files, will be erased."
        sleep $stime
        echo "CTRL+C not pressed. Continuing..."
        mkdir -p $HOME/docker
        cp -r /usr/gsh/docker $HOME
        if [ -f /usr/bin/sudo ]
        then
            if [ $EUID -eq 0 ]
            then
                cd /usr
                mv ./gsh /tmp
                cd - > /dev/null
                sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
                echo "Uninstall completed."
            elif [ $EUID -ge 1000 ]
            then
                cd /usr
                sudo mv ./gsh /tmp
                cd - > /dev/null
                sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
                echo "Uninstall completed."
            fi
        elif ! [ -f /usr/bin/sudo ]
        then
            cd /usr
            mv ./gsh /tmp
            cd - > /dev/null
            sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
            echo "Uninstall completed."
        fi
    elif [ $num -eq 2 ]
    then
        x=300
        stime=$x
        echo "Understood. Archiving docker folder to $PWD/gsh-docker-archive.tar.gz and deleting /usr/gsh . Please ensure you have a backup of any custom files prior to running this script. If you do NOT have a backup of your custom files please press CTRL+C within the next $((x/60)) minutes otherwise your custom files, not including docker folder files, will be erased."
        sleep $stime
        echo "CTRL+C not pressed. Continuing..."
        tar -czf gsh-docker-archive.tar.gz /usr/gsh/docker
        if [ -f /usr/bin/sudo ]
        then
            if [ $EUID -eq 0 ]
            then
                cd /usr
                mv ./gsh /tmp
                cd - > /dev/null
                sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
                echo "Uninstall completed."
            elif [ $EUID -ge 1000 ]
            then
                cd /usr
                sudo mv ./gsh /tmp
                cd - > /dev/null
                sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
                echo "Uninstall completed."
            fi
        elif ! [ -f /usr/bin/sudo ]
        then
            cd /usr
            mv ./gsh /tmp
            cd - > /dev/null
            sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
            echo "Uninstall completed."
        fi
    elif [ $num -eq 3 ]
    then
        if [ -f /usr/bin/sudo ]
        then
            if [ $EUID -eq 0 ]
            then
                echo "Understood. Archiving docker folder to $PWD/gsh-docker-archive.tar.gz ."
                tar -czf gsh-docker-archive.tar.gz /usr/gsh/docker
            elif [ $EUID -ge 1000 ]
            then
                echo "Understood. Archiving docker folder to $PWD/gsh-docker-archive.tar.gz ."
                sudo tar -czf gsh-docker-archive.tar.gz /usr/gsh/docker
            fi
        elif ! [ -f /usr/bin/sudo ]
        then
            echo "Understood. Archiving docker folder to $PWD/gsh-docker-archive.tar.gz ."
            tar -czf gsh-docker-archive.tar.gz /usr/gsh/docker
        fi
    fi
elif [ "$ans" == "no" ]
then
    echo "Understood. Deleting entire folder and removing aliases from $HOME/.bashrc"
    if [ -f /usr/bin/sudo ]
    then
        if [ $EUID -eq 0 ]
        then
            cd /usr
            mv ./gsh /tmp
            cd - > /dev/null
            sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
            echo "Uninstall completed."
        elif [ $EUID -ge 1000 ]
        then
            cd /usr
            sudo mv ./gsh /tmp
            cd - > /dev/null
            sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
            echo "Uninstall completed."
        fi
    elif ! [ -f /usr/bin/sudo ]
    then
        cd /usr
        mv ./gsh /tmp
        cd - > /dev/null
        sed -i "s.alias gsh='bash /usr/gsh/script-files/gsh'.alias gsh='bash /tmp/gsh/script-files/gsh.g" $HOME/.bashrc
        echo "Uninstall completed."
    fi
fi
